services:
  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    env_file: ${PLAYDAY_ENV_FILE:-./.env}
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.playday/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.playday/rabbitmq/log/:/var/log/rabbitmq/
  mongodb:
    image: mongodb:8.0.15
    build: ./mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/.playday/mongodb/data/db:/data/db
    env_file: ${PLAYDAY_ENV_FILE:-./.env}
    command: ["-f", "/etc/mongod.conf"]
  nginx:
    image: nginx:1.29.1-alpine
    env_file: ${PLAYDAY_ENV_FILE:-./.env}
    build: 
      context: ./nginx
      args:
        PROTOCOL: ${PROTOCOL:-HTTP}
        EXTERNAL_HTTP_PORT: ${EXTERNAL_HTTP_PORT:-80}
        EXTERNAL_HTTPS_PORT: ${EXTERNAL_HTTPS_PORT:-443}
        WS_LOCAL_PORT: ${WS_LOCAL_PORT:-3005}
        SERVER_NAME: ${NEXT_PUBLIC_BASE_URL:-localhost}
    restart: always
    ports:
      - ${EXTERNAL_HTTP_PORT:-80}:${EXTERNAL_HTTP_PORT:-80}
      - ${EXTERNAL_HTTPS_PORT:-443}:${EXTERNAL_HTTPS_PORT:-443}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ~/.playday/ssldata/certbot/conf:/etc/letsencrypt
      - ~/.playday/ssldata/certbot/www:/var/www/certbot
      - ~/.playday/public/gen:/var/public/gen
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ~/.playday/ssldata/certbot/conf:/etc/letsencrypt
      - ~/.playday/ssldata/certbot/www:/var/www/certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  taskserver:
    image: ghcr.io/sophluent-systems/playdayai/taskserver:latest
    env_file: ${PLAYDAY_ENV_FILE:-./.env}
    build: 
      context: ./
      dockerfile: taskserver/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
        WS_LOCAL_PORT: ${WS_LOCAL_PORT:-3005}
    restart: always
    volumes:
      - ~/.playday/public/gen:/app/public/gen
    deploy:
      resources:
        limits:
          memory: 20G
        reservations:
          memory: 10G       
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
