import { Constants } from '@src/common/defaultconfig';
import { ifThenElseMetadata } from '@src/common/nodeMetadata';

export const nodeTypeMenus = {
  start: [{
    /*  SUBSECTION */
    label: "Start",
    type: "fieldlist",
    fields: [
      {
        label: "Text (Optional, shown at the start)",
        type: "text",
        path: "params.text",
        maxChar: 2048,
        multiline: true,
        lines: 4,
        defaultValue: "Welcome!",
      },
    ],
  }],
  staticText: [{
    /*  SUBSECTION */
    label: "Static Text",
    type: "fieldlist",
    fields: [
      {
        label: "Name (name referenced in input and ouput dropdowns)",
        type: "text",
        path: "instanceName",
        tooltip: "A unique name for your reference.",
        maxChar: 30,
        multiline: false,
        defaultValue: "mainUserInput",
      },
      {
        label: "Text",
        type: "text",
        path: "params.text",
        maxChar: 16000,
        multiline: true,
        lines: 8,
        defaultValue: "This is some text.",
      },
    ],
  }],
  delay: [{
    /*  SUBSECTION */
    label: "Delay",
    type: "fieldlist",
    fields: [
      {
        label: "Name (name referenced in input and ouput dropdowns)",
        type: "text",
        path: "instanceName",
        tooltip: "A unique name for your reference.",
        maxChar: 30,
        multiline: false,
        defaultValue: "mainUserInput",
      },
      {
        label: "Delay (Seconds)",
        type: "float",
        path: "params.delay",
        range: [0.25, 10000.0],
        tooltip: "Delay time in seconds.",
        defaultValue: 1,
      },
    ],
  }],
  randomNumber: [{
    /*  SUBSECTION */
    label: "Random Number",
    type: "fieldlist",
    fields: [
      {
        label: "Name (name referenced in input and ouput dropdowns)",
        type: "text",
        path: "instanceName",
        tooltip: "A unique name for your reference.",
        maxChar: 30,
        multiline: false,
        defaultValue: "mainUserInput",
      },
      {
        label: "Low (inclusive)",
        type: "float",
        path: "params.low",
        range: [0, 1000000000],
        tooltip: "Low end of the random number range.",
        defaultValue: 0,
      },
      {
        label: "High (exclusive)",
        type: "float",
        path: "params.high",
        range: [0, 1000000000],
        tooltip: "High end of the random number range.",
        defaultValue: 1,
      },
      {
        label: "Number Type",
        type: "dropdown",
        path: "params.numberType",
        tooltip: "Type of number to generate.",
        options: ["integer", "float"].map((option) => {return {label: option, value: option}}),
        defaultValue: "integer",
      },
    ],
  }],
    externalTextInput: [{
      /*  SUBSECTION */
      label: "User Input Node",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "mainUserInput",
        },
        {
          label: "User Token Limit",
          type: "decimal",
          path: "params.tokenLimit",
          range: [10, 10000],
          tooltip: "The maximum number of tokens that can be typed by the user in a single turn.",
          defaultValue: 100,
        },
      ],
    }],
    externalMultiInput: [{
      /*  SUBSECTION */
      label: "Multi-input Node",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "User input",
        },
        {
          label: "Supported input types",
          path: "params.supportedTypes",
          type: "multiselect",
          tooltip: "The types of input that are supported by this node.",
          defaultValue: ["text", "audio"],
          options: ["text", "audio", "image", "video"].map((option) => {return {label: option, value: option}}),
        },
        {
          label: "Text Token Limit",
          type: "decimal",
          path: "params.tokenLimit",
          range: [10, 10000],
          tooltip: "The maximum number of tokens that can be typed by the user in a single turn.",
          defaultValue: 100,
        },
        {
          label: "Conversational (send speech automatically on stop talking)",
          path: "params.conversational",
          type: "checkbox",
          defaultValue: true,
          tooltip: "If selected, the audio will be sent automatically after the user stops talking.",
        },
      ],
    }],
    llm: [{  
      /*  SUBSECTION */
      label: "LLM Node",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "mainAssistant",
        },
        {
          label: "Context (main instructions for the AI)",
          type: "text",
          path: "params.context",
          migratePath: "rules",
          tooltip: "This is the main assistant instructions.",
          maxChar: 16000,
          multiline: true,
          lines: 20,
          defaultValue: "Answer the user's questions and provide helpful information.",
        },
        {
          label: "Pre-first-turn Instructions (used before the 1st user turn)",
          type: "text",
          path: "params.zerothTurnInstructions",
          migratePath: "greetingInstructions",
          tooltip: "Give the AI instructions on what to say to start the chat.",
          maxChar: 4096,
          multiline: true,
          lines: 6,
          defaultValue: "",
        },
        {
          label: "Turn Instructions (given each turn after the overview)",
          type: "text",
          path: "params.turnInstructions",
          migratePath: "turnInstructions",
          tooltip: "Give the AI instructions on what to do when the player plays a turn.",
          maxChar: 4096,
          multiline: true,
          lines: 6,
          defaultValue: "",
        },
        {
          label: "AI Parameters",
          type: "llmparams",
          fields: [
            {
              label: "AI Input Format",
              path: "params.inputFormat",
              type: "dropdown",
              tooltip: "Format to send to the main LLM that comes up with a response to the user.",
              options: Constants.modelRequestFormats.inputOptions.map((option) => {return {label: option, value: option}}),
            },
            {
              label: "AI Output Format",
              path: "params.outputFormat",
              type: "dropdown",
              tooltip: "Format to send to the main LLM that comes up with a response to the user.",
              options: Constants.modelRequestFormats.outputOptions.map((option) => {return {label: option, value: option}}),
            },
            {
              label: "Server URL",
              type: "text",
              path: "params.serverUrl",
              tooltip: "URL for making requests to the server. Format: ws://example.com:5005/api/v1/stream",
              maxChar: 2048,
              multiline: false,
            },
            {
              label: "API Key (ignored for local models)",
              path: "params.apiKey",
              type: "text",
              tooltip: "API key for requests to the server.",
              maxChar: 512,
              defaultValue: 'setting:openAIkey;sk-xxxxxxxxxxxxxxxxxxxxxxxx',
              multiline: false,
            },
            {
              label: "Temperature (Creativity) 0.0 - 1.0",
              type: "float",
              path: "params.temperature",
              migratePath: "temperature",
              tooltip: "Lower numbers mean less creative freedom, higher numberes is higher.",
              range: [0.01, 2.0],
              defaultValue: 0.7,
            },
            {
              label: "New token target",
              type: "decimal",
              range: [10, 10000],
              path: "params.newTokenTarget",
              migratePath: "assistantTokenLimit",
              tooltip: "The target length of the server's response.",
              defaultValue: 250,
            },
            {
              label: "Token Limit",
              type: "decimal",
              range: [10, 10000],
              path: "params.tokenLimit",
              migratePath: "assistantTokenLimit",
              tooltip: "The maximum number of tokens that can be processed by the server a single turn.",
              defaultValue: 4096,
            },
            {
              label: "Top_p",
              type: "float",
              range: [0.01, 1.0],
              path: "params.top_p",
              tooltip: "If not set to 1, select tokens with probabilities adding up to less than this number. Higher value = higher range of possible random results.",
              defaultValue: 0.92,
            },
            {
              label: "Top_k",
              type: "decimal",
              range: [1, 200],
              path: "params.top_k",
              tooltip: "Similar to top_p, but select instead only the top_k most likely tokens. Higher value = higher range of possible random results.",
              defaultValue: 8,
            },
            {
              label: "Repetition_penalty",
              type: "float",
              range: [1.0, 1.5],
              path: "params.repetition_penalty",
              tooltip: "Exponential penalty factor for repeating prior tokens. 1 means no penalty, higher value = less repetition, lower value = more repetition.",
              defaultValue: 1.1,
            },
            {
              label: "Streaming response",
              type: "checkbox",
              path: "params.streaming",
              tooltip: "If selected, the AI will send responses as they are generated.",
              defaultValue: true,
            },
          ]
        }
      ],
    }],
    llmData: [{  
      /*  SUBSECTION */
      label: "LLM Node",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "mainAssistant",
        },
        {
          label: "Context (main instructions for the AI)",
          type: "text",
          path: "params.context",
          migratePath: "rules",
          tooltip: "This is the main assistant instructions.",
          maxChar: 16000,
          multiline: true,
          lines: 20,
          defaultValue: "Answer the user's questions and provide helpful information.",
        },
        {
          label: "Pre-first-turn Instructions (used before the 1st user turn)",
          type: "text",
          path: "params.zerothTurnInstructions",
          migratePath: "greetingInstructions",
          tooltip: "Give the AI instructions on what to say to start the chat.",
          maxChar: 4096,
          multiline: true,
          lines: 6,
          defaultValue: "",
        },
        {
          label: "Turn Instructions (given each turn after the overview)",
          type: "text",
          path: "params.turnInstructions",
          migratePath: "turnInstructions",
          tooltip: "Give the AI instructions on what to do when the player plays a turn.",
          maxChar: 4096,
          multiline: true,
          lines: 6,
          defaultValue: "",
        },
        {
          label: "Data fields to extract from the AI's output (comma separated):",
          type: "dataFieldsEditor",
          path: "params.outputDataFields",
          tooltip: "Data fields to request from the AI.",
          defaultValue: [],
        },
        {
          label: "AI Parameters",
          type: "llmparams",
          fields: [
            {
              label: "AI Input Format",
              path: "params.inputFormat",
              type: "dropdown",
              tooltip: "Format to send to the main LLM that comes up with a response to the user.",
              options: Constants.modelRequestFormats.inputOptions.map((option) => {return {label: option, value: option}}),
            },
            {
              label: "AI Output Format",
              path: "params.outputFormat",
              type: "dropdown",
              tooltip: "Format to send to the main LLM that comes up with a response to the user.",
              options: Constants.modelRequestFormats.outputOptions.map((option) => {return {label: option, value: option}}),
            },
            {
              label: "Server URL",
              type: "text",
              path: "params.serverUrl",
              tooltip: "URL for making requests to the server. Format: ws://example.com:5005/api/v1/stream",
              maxChar: 2048,
              multiline: false,
            },
            {
              label: "API Key (ignored for local models)",
              path: "params.apiKey",
              type: "text",
              tooltip: "API key for requests to the server.",
              maxChar: 512,
              defaultValue: 'setting:openAIkey;sk-xxxxxxxxxxxxxxxxxxxxxxxx',
              multiline: false,
            },
            {
              label: "Temperature (Creativity) 0.0 - 1.0",
              type: "float",
              path: "params.temperature",
              migratePath: "temperature",
              tooltip: "Lower numbers mean less creative freedom, higher numberes is higher.",
              range: [0.01, 2.0],
              defaultValue: 0.7,
            },
            {
              label: "New token target",
              type: "decimal",
              range: [10, 10000],
              path: "params.newTokenTarget",
              migratePath: "assistantTokenLimit",
              tooltip: "The target length of the server's response.",
              defaultValue: 250,
            },
            {
              label: "Token Limit",
              type: "decimal",
              range: [10, 10000],
              path: "params.tokenLimit",
              migratePath: "assistantTokenLimit",
              tooltip: "The maximum number of tokens that can be processed by the server a single turn.",
              defaultValue: 4096,
            },
            {
              label: "Top_p",
              type: "float",
              range: [0.01, 1.0],
              path: "params.top_p",
              tooltip: "If not set to 1, select tokens with probabilities adding up to less than this number. Higher value = higher range of possible random results.",
              defaultValue: 0.92,
            },
            {
              label: "Top_k",
              type: "decimal",
              range: [1, 200],
              path: "params.top_k",
              tooltip: "Similar to top_p, but select instead only the top_k most likely tokens. Higher value = higher range of possible random results.",
              defaultValue: 8,
            },
            {
              label: "Repetition_penalty",
              type: "float",
              range: [1.0, 1.5],
              path: "params.repetition_penalty",
              tooltip: "Exponential penalty factor for repeating prior tokens. 1 means no penalty, higher value = less repetition, lower value = more repetition.",
              defaultValue: 1.1,
            },
            {
              label: "Streaming response",
              type: "checkbox",
              path: "params.streaming",
              tooltip: "If selected, the AI will send responses as they are generated.",
              defaultValue: true,
            },
          ]
        }
      ],
    }],
    fileStore: [{  
      /*  SUBSECTION */
      label: "File Store",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "mainAssistant",
        },
        {
          label: "Files",
          type: "fileStoreEditor",
          path: "params.files",
          tooltip: "Files stored.",
          defaultValue: [],
        },
      ],
    }],
    imageGenerator: [{  
      /*  SUBSECTION */
      label: "Image Generator Node",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "mainAssistant",
        },
        {
          label: "Prompt (instructions used to generate the image)",
          type: "text",
          path: "params.prompt",
          tooltip: "The instructions for generating the image (often overridden by input)",
          maxChar: 2000,
          multiline: true,
          lines: 4,
          defaultValue: "An image of a dog in a field of flowers.",
        },
        {
          label: "Width",
          type: "decimal",
          range: [512, 4320],
          path: "params.width",
          tooltip: "The requested width of the image.",
        },
        {
          label: "Height",
          type: "decimal",
          range: [512, 4320],
          path: "params.height",
          tooltip: "The requested height of the image.",
        },
        {
          label: "Extra Parameters",
          type: "text",
          path: "params.extraPromptParams",
          tooltip: "Extra parameters to append to the prompt",
          maxChar: 500,
          multiline: true,
        },
        {
          label: "Negative prompt",
          type: "text",
          path: "params.negativePrompt",
          tooltip: "Negative prompt parameters to send to the server.",
          maxChar: 500,
          multiline: true,
        },
        {
          label: "AI Parameters",
          type: "imagegenparams",
          fields: [
            {
              label: "Server URL",
              type: "text",
              path: "params.serverUrl",
              tooltip: "URL for making requests to the server. Format: ws://example.com:5005/api/v1/stream",
              maxChar: 2048,
              multiline: false,
            },
            {
              label: "API Key (ignored for local models)",
              path: "params.apiKey",
              type: "text",
              tooltip: "API key for requests to the server.",
              maxChar: 512,
              defaultValue: 'setting:openAIkey;sk-xxxxxxxxxxxxxxxxxxxxxxxx',
              multiline: false,
            },
            {
              label: "Seed",
              type: "decimal",
              range: [-1, Number.MAX_SAFE_INTEGER],
              path: "params.seed",
              tooltip: "A seed specific to the image generator.",
            },
            {
              label: "Stable Diffustion Advanced Parameters",
              type: "subSection",
              fields: [
                {
                  label: "Sampling steps",
                  type: "decimal",
                  range: [1, 500],
                  path: "params.steps",
                  tooltip: "Sampling steps - usually, more leads to a higher quality image but takes more time.",
                  defaultValue: 20,
                },
                {
                  label: "CFG Scale (Stable Diffusion)",
                  type: "float",
                  range: [0.5, 30.0],
                  path: "params.cfg_scale",
                  tooltip: "CFG Scale.",
                  defaultValue: 7,
                },
                {
                  label: "Prompt Token Limit (0 = no limit) (Stable Diffusion)",
                  type: "decimal",
                  range: [0, 1000],
                  path: "params.promptTokenLimit",
                  tooltip: "Max tokens for prompt and negative prompt (same value used for both)",
                  defaultValue: 70,
                },
                {
                  label: "Sampling method (Stable Diffusion)",
                  type: "text",
                  maxChar: 256,
                  path: "params.sampling_method",
                  tooltip: "Sampling method.",
                  defaultValue: "Euler a",
                },
              ]
            }
          ]
        }
      ],
    }],    
    codeBlock: [{  
      /*  SUBSECTION */
      label: "Code Block",
      type: "fieldlist",
      fields: [ 
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "Code Block",
        },
        {
          label: "Code to run:",
          type: "codeEditor",
          path: "params.code_UNSAFE",
          tooltip: "Code to run",
          defaultValue: "",
        },
      ],
    }],    
    scenario: [{  
      /*  SUBSECTION */
      label: "Scenarios",
      type: "fieldlist",
      fields: [ 
        {
          label: "Give this new entry a name to help you keep track of it (not shown to users):",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "Code Block",
        },
        {
          label: "Minimum Frequency",
          type: "decimal",
          range: [1, 10000],
          path: "params.frequencyMin",
          tooltip: "Minimum time bewteen scenarios.",
        },
        {
          label: "Maximum Frequency",
          type: "decimal",
          range: [1, 10000],
          path: "params.frequencyMax",
          tooltip: "Minimum time bewteen scenarios.",
        },
        {
          label: "Scenarios",
          type: "scenarioEditor",
          path: "params.catalog",
          tooltip: "Scenarios",
          defaultValue: [],
        },
      ],
    }],
    stt: [{  
      /*  SUBSECTION */
      label: "Speech-to-text Node",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "STT",
        },
        {
          label: "AI Parameters",
          type: "fieldlist",
          fields: [
            {
              label: "Model",
              type: "text",
              path: "params.model",
              tooltip: "Model to use",
              maxChar: 50,
              multiline: false,
              defaultValue: "gpt-4o-transcribe",
            },
            {
              label: "Server URL",
              type: "text",
              path: "params.serverUrl",
              tooltip: "URL for making requests to the server.",
              maxChar: 2048,
              multiline: false,
              default: 'https://api.openai.com/v1/audio/transcriptions',
            },
            {
              label: "API Key (ignored for local models)",
              path: "params.apiKey",
              type: "text",
              tooltip: "API key for requests to the server.",
              maxChar: 512,
              defaultValue: 'setting:openAIkey;sk-xxxxxxxxxxxxxxxxxxxxxxxx',
              multiline: false,
            },
          ]
        }
      ],
    }],
    tts: [{  
      /*  SUBSECTION */
      label: "Text-to-Speech Node",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "TTS",
        },
        {
          label: "Text to convert to speech",
          type: "text",
          path: "params.text",
          tooltip: "The text to convert",
          maxChar: 2000,
          multiline: true,
          lines: 4,
          defaultValue: "The quick brown fox jumped over the lazy dog.",
        },
        {
          label: "Speed",
          type: "float",
          range: [0.25, 4.0],
          path: "params.speed",
          tooltip: "The requested playback speed.",
          defaultValue: 1,
        },
        {
          label: "Voice",
          path: "params.voice",
          type: "text",
          maxChar: 200,
          multiline: false,
          defaultValue: "alloy",
        },
        {
          label: "AI Parameters",
          type: "audiogenparams",
          fields: [
            {
              label: "Server URL",
              type: "text",
              path: "params.serverUrl",
              tooltip: "URL for making requests to the server.",
              maxChar: 2048,
              multiline: false,
              default: 'https://api.openai.com/v1/audio/speech',
            },
            {
              label: "API Key (ignored for local models)",
              path: "params.apiKey",
              type: "text",
              tooltip: "API key for requests to the server.",
              maxChar: 512,
              defaultValue: 'setting:openAIkey;sk-xxxxxxxxxxxxxxxxxxxxxxxx',
              multiline: false,
            },
          ]
        }
      ],
    }],
    audioPlayback: [{  
      /*  SUBSECTION */
      label: "Audio Playback Node",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "TTS",
        },
        {
            label: "Audio Type",
            type: "dropdown",
            path: "params.audioType",
            options: Constants.audioPlaybackTypes,
            defaultValue: "speech",
            tooltip: "Type of audio to play.",
        },
        {
            label: "Loop",
            type: "checkbox",
            path: "params.loop",
            defaultValue: false,
            tooltip: "Loop the audio.",
        },
        {
            label: "Autoplay",
            type: "dropdown",
            path: "params.autoplay",
            defaultValue: "onlyFirstTime",
            options: [
                {label: "Never", value: "never"},
                {label: "Only first time", value: "onlyFirstTime"},
                {label: "Always", value: "always"},
            ],
            tooltip: "Autoplay setting.",
        },
        {
          label: "Text to display",
          type: "text",
          path: "params.text",
          maxChar: 16000,
          multiline: true,
          lines: 8,
          defaultValue: "",
        },
        {
          label: "Hide message (if selected, audio plays in the background with no controls)",
          type: "checkbox",
          path: "params.hidden",
          defaultValue: true,
          tooltip: "If selected, audio plays in the background with no controls",
        },
      {
        label: "Speed",
        type: "float",
        range: [0.25, 4.0],
        path: "params.speed",
        tooltip: "The requested playback speed.",
      },
    ],
  }],
  suggestions: [{
      /*  SUBSECTION */
      label: "suggestions",
      type: "subSection",
      fields: [
        {
          label: "Suggestions instructions",
          type: "text",
          path: "features.suggestions.instructions",
          tooltip: "Instructions for generating suggestions.",
          maxChar: 2048,
          multiline: false,
          defaultValue: "An array of 4 different possible actions the player could take for their character based on what's happening in the game, being plausible, specific, and brief",
        },
      ]
    }],    
    forLoop: [{  
      /*  SUBSECTION */
      label: "For Loop",
      type: "fieldlist",
      fields: [ 
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "For loop",
        },
        {
          label: "From",
          type: "decimal",
          range: [0, 9999999],
          path: "params.start",
          defaultValue: 0,
          tooltip: "Starting value of the for loop.",
        },
        {
          label: "To",
          type: "decimal",
          range: [0, 9999999],
          path: "params.end",
          defaultValue: 10,
          tooltip: "Starting value of the for loop.",
        },
      ],
    }],
    ifThenElse:  [{  
      /*  SUBSECTION */
      label: "For Loop",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "If/Then",
        },
        {
          label: "Comparison",
          path: "params.comparator",
          type: "dropdown",
          options: ifThenElseMetadata.supportedComparators.map((option) => {return {label: option, value: option}}),
          defaultValue: "==",
          tooltip: "Comparison operator to use to compare the two values.",
        },
        {
          label: "Default input value (overridden by input)",
          path: "params.value",
          type: "text",
          tooltip: "The default input value.",
          maxChar: 1000,
          multiline: false,
          defaultValue: "0",
        },
        {
          label: "Comparison Value (uses JS eval)",
          type: "text",
          path: "params.compareValue",
          tooltip: "The value to compare against.",
          maxChar: 1000,
          multiline: false,
          defaultValue: "true",
        },
      ],
    }],   
    arrayIndex: [{  
      /*  SUBSECTION */
      label: "Array Index",
      type: "fieldlist",
      fields: [ 
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "For loop",
        },
      ],
    }], 
    arrayIterator: [{  
      /*  SUBSECTION */
      label: "Array Index",
      type: "fieldlist",
      fields: [ 
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "For loop",
        },
      ],
    }],
    whileLoop:  [{  
      /*  SUBSECTION */
      label: "While Loop",
      type: "fieldlist",
      fields: [
        {
          label: "Name (name referenced in input and ouput dropdowns)",
          type: "text",
          path: "instanceName",
          tooltip: "A unique name for your reference.",
          maxChar: 30,
          multiline: false,
          defaultValue: "While",
        },
        {
          label: "Comparison",
          path: "params.comparator",
          type: "dropdown",
          options: ifThenElseMetadata.supportedComparators.map((option) => {return {label: option, value: option}}),
          defaultValue: "==",
          tooltip: "Comparison operator to use to compare the two values.",
        },
        {
          label: "Default input value (overridden by input)",
          path: "params.value",
          type: "text",
          tooltip: "The default input value.",
          maxChar: 1000,
          multiline: false,
          defaultValue: "0",
        },
        {
          label: "Comparison Value (uses JS eval)",
          type: "text",
          path: "params.compareValue",
          tooltip: "The value to compare against.",
          maxChar: 1000,
          multiline: false,
          defaultValue: "true",
        },
      ],
    }],
  };
