import {
  Brain,
  Activity,
  Monitor,
  Minimize2,
  Hammer,
  AlertTriangle,
  MessageCircle,
  UserRound,
  Plus,
  CircleUser,
  Accessibility,
  Armchair,
  Bot,
  PawPrint,
  Briefcase,
  GraduationCap,
  FirstAidKit,
  Dumbbell,
  CookingPot,
  Coffee,
  Flower2,
  BookOpen,
  Wine,
  Paintbrush,
  Camera,
  Bike,
  Smile,
  Heart,
  Plane,
  Users,
  Ear,
  Mountain,
  Home,
  Hourglass,
  Languages,
  Laptop,
  Music,
  Bell,
  Palette,
  Trees,
  Smartphone,
  Waves,
  Utensils,
  Ship,
  ShoppingCart,
  Leaf,
  Gamepad2,
  Football,
  ThumbsUp,
  Train,
  Eye,
  Sun,
  CalendarDays,
} from 'lucide-react';

const fallbackIcon = UserRound;

export const PersonaIcons = {
  Psychology: Brain,
  RunCircle: Activity,
  DesktopWindows: Monitor,
  Compress: Minimize2,
  Handyman: Hammer,
  Warning: AlertTriangle,
  Chat: MessageCircle,
  Person: UserRound,
  Add: Plus,
  AccountCircle: CircleUser,
  AccessibilityNew: Accessibility,
  AirlineSeatIndividualSuite: Armchair,
  Android: Bot,
  Pets: PawPrint,
  Work: Briefcase,
  School: GraduationCap,
  LocalHospital: FirstAidKit,
  FitnessCenter: Dumbbell,
  Kitchen: CookingPot,
  LocalCafe: Coffee,
  LocalFlorist: Flower2,
  LocalLibrary: BookOpen,
  LocalBar: Wine,
  Brush: Paintbrush,
  CameraAlt: Camera,
  DirectionsBike: Bike,
  EmojiPeople: Smile,
  Face: Smile,
  Favorite: Heart,
  Flight: Plane,
  Group: Users,
  Hearing: Ear,
  Hiking: Mountain,
  Home: Home,
  HourglassEmpty: Hourglass,
  Language: Languages,
  LaptopMac: Laptop,
  MusicNote: Music,
  Notifications: Bell,
  Palette: Palette,
  Park: Trees,
  PhoneAndroid: Smartphone,
  Pool: Waves,
  Restaurant: Utensils,
  Rowing: Ship,
  ShoppingCart: ShoppingCart,
  Spa: Leaf,
  SportsEsports: Gamepad2,
  SportsSoccer: Football,
  ThumbUp: ThumbsUp,
  Train: Train,
  Visibility: Eye,
  WbSunny: Sun,
  Weekend: CalendarDays,
};

export function resolvePersonaIcon(iconId) {
  return PersonaIcons[iconId] || fallbackIcon;
}
