import {
    Psychology, RunCircle, DesktopWindows, Compress, Handyman, Warning,
    Chat, Person, Add, AccountCircle, AccessibilityNew,
    AirlineSeatIndividualSuite, Android, Pets, Work, School, LocalHospital,
    FitnessCenter, Kitchen, LocalCafe, LocalFlorist, LocalLibrary, LocalBar,
    Brush, CameraAlt, DirectionsBike, EmojiPeople, Face, Favorite,
    Flight, Group, Hearing, Hiking, Home, HourglassEmpty, Language, LaptopMac,
    MusicNote, Notifications, Palette, Park, PhoneAndroid, Pool, Restaurant,
    Rowing, ShoppingCart, Spa, SportsEsports, SportsSoccer, ThumbUp, Train,
    Visibility, WbSunny, Weekend,
} from "@mui/icons-material";

export const PersonaIcons = {
    "Psychology": Psychology,
    "RunCircle": RunCircle,
    "DesktopWindows": DesktopWindows,
    "Compress": Compress,
    "Handyman": Handyman,
    "Warning": Warning,
    "Chat": Chat,
    "Person": Person,
    "Add": Add,
    "AccountCircle": AccountCircle,
    "AccessibilityNew": AccessibilityNew,
    "AirlineSeatIndividualSuite": AirlineSeatIndividualSuite,
    "Android": Android,
    "Pets": Pets,
    "Work": Work,
    "School": School,
    "LocalHospital": LocalHospital,
    "FitnessCenter": FitnessCenter,
    "Kitchen": Kitchen,
    "LocalCafe": LocalCafe,
    "LocalFlorist": LocalFlorist,
    "LocalLibrary": LocalLibrary,
    "LocalBar": LocalBar,
    "Brush": Brush,
    "CameraAlt": CameraAlt,
    "DirectionsBike": DirectionsBike,
    "EmojiPeople": EmojiPeople,
    "Face": Face,
    "Favorite": Favorite,
    "Flight": Flight,
    "Group": Group,
    "Hearing": Hearing,
    "Hiking": Hiking,
    "Home": Home,
    "HourglassEmpty": HourglassEmpty,
    "Language": Language,
    "LaptopMac": LaptopMac,
    "MusicNote": MusicNote,
    "Notifications": Notifications,
    "Palette": Palette,
    "Park": Park,
    "PhoneAndroid": PhoneAndroid,
    "Pool": Pool,
    "Restaurant": Restaurant,
    "Rowing": Rowing,
    "ShoppingCart": ShoppingCart,
    "Spa": Spa,
    "SportsEsports": SportsEsports,
    "SportsSoccer": SportsSoccer,
    "ThumbUp": ThumbUp,
    "Train": Train,
    "Visibility": Visibility,
    "WbSunny": WbSunny,
    "Weekend": Weekend,
    // Additional icons as needed
};
