permissions:
  contents: read
  packages: write

env:
  NODE_ENV: production
  NEXT_PUBLIC_WS_PORT: 3005

steps:
  - uses: actions/checkout@v4

  - name: Compute IMAGE (lowercase)
    run: |
      echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}/taskserver" >> $GITHUB_ENV

  - uses: docker/setup-buildx-action@v3

  - uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  - uses: docker/build-push-action@v6
    with:
      context: .
      file: taskserver/Dockerfile
      push: true
      tags: |
        ${{ env.IMAGE }}:latest
        ${{ env.IMAGE }}:${{ github.sha }}
      build-args: |
        NODE_ENV=${{ env.NODE_ENV }}
        NEXT_PUBLIC_WS_PORT=${{ env.NEXT_PUBLIC_WS_PORT }}
